spring:
  application:
    name: webservice1
eureka:
  client:
    serviceUrl: http://localhost:8761/webservice1/
      defaultZone: http://localhost:8761/eureka/
  healthcheck:
    enabled: true
